LLM_MODEL = "llama3.2:3b"

MAX_QUERIES = 8
MAX_PAPERS_PER_QUERY = 10
MAX_PAPERS_TOTAL = 100
MAX_PAPERS_PER_SOURCE = 8
MAX_NAMES = 100
MAX_FULLTEXT_FETCHES = 100
DEFAULT_SUGGESTED_COLUMNS = 8
OUTPUT_PATH = "dataset.csv"

RELEVANCE_THRESHOLD = 0.65
VALIDITY_THRESHOLD = 0.70
VALIDATION_SCORE_THRESHOLD = 0.65

HTTP_TIMEOUT_SECONDS = 20
